version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: chapter-04-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=Inn3315400371
        - MYSQL_DATABASE=lara_vue
        - MYSQL_USER=test_root
        - MYSQL_PASSWORD=88888888
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: chapter-04-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8081:80"
      links:
        - mysql

    php-fpm:
      build: phpdocker/php-fpm
      container_name: chapter-04-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        MYSQL_USER: chapter-04
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: 123456
      ports:
        - "8085:80"
      volumes:
         - .:/application
      links:
        - mysql

    memcached:
      image: memcached:alpine
      container_name: laravel-angular-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: laravel-angular-mailhog
      ports:
        - "8082:8025"

    redis:
      image: redis:alpine
      container_name: laravel-angular-redis